micronaut:
  application:
    name: mnatPrepersistPoc
  server:
    port: 8080
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: jdbc:tc:postgresql://localhost/mnatPrepersistPoc
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: mnatPrepersistPoc
    password: mnatPrepersistPoc

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false

logger:
  levels:
    com.mnaut.poc: DEBUG
    ROOT: DEBUG